name: PunchTree-Minigames
main: net.punchtree.minigames.MinigamesPlugin
version: 0.3.1
api-version: 1.15
depend: [PunchTreeUtil]
description: Common code and series of libraries for creating PvP minigames in Minecraft