name: PunchTree-Minigames
main: net.punchtree.minigames.MinigamesPlugin
version: 0.6.1
api-version: 1.17
depend: [PunchTree-Util]
description: Common code and series of libraries for creating PvP minigames in Minecraft

commands:
   ## This defined here allows it not being red, and being used in lobbies (in addition to all preprocessing in minigame impls)
   leave: